/* Criar o banco de dados */
CREATE DATABASE DB_TGS;

/* Usar o banco correto */
USE DB_TGS;

/* Criar tabela de procedimentos */
CREATE TABLE TB_PROCEDURES (
	ID_PROCEDURE INT PRIMARY KEY IDENTITY NOT NULL,
	PROCEDURE_TITLE VARCHAR(20)
);

/* Criar tabela de pacientes */
CREATE TABLE TB_PATIENTS (
	CPF_PATIENT VARCHAR(14) PRIMARY KEY NOT NULL,
	RG_PATIENT VARCHAR(12) UNIQUE NOT NULL,
	NAME_PATIENT VARCHAR(20),
	LAST_NAME VARCHAR(40),
	NICKNAME VARCHAR(20),
	BIRTH_DATE DATE,
	HEIGHT DECIMAL(18,2),
	WEIGHT_PATIENT DECIMAL(18,2),
	EMAIL VARCHAR(40),
	TELEPHONE VARCHAR(13),
	CELLPHONE VARCHAR(14),
	STREET VARCHAR(50),
	NEIGHBORHOOD VARCHAR(20),
	CITY VARCHAR(30),
	DISTRICT VARCHAR(20),
	CEP VARCHAR(10),
	COMPLEMENT VARCHAR(15),
	NUMBER INT
);

/* Criar a tabela de dentistas */
CREATE TABLE TB_DENTISTA (
	CRO_DENTIST VARCHAR(6) PRIMARY KEY NOT NULL,
	NAME_DENTIST VARCHAR(20),
	LAST_NAME VARCHAR(40),
	EXPERTISE VARCHAR(15)
);

CREATE TABLE TB_EMPLOYEES (
	CPF_EMPLOYEE VARCHAR(14) PRIMARY KEY NOT NULL,
	NAME_EMPLOYEE VARCHAR(20),
	LAST_NAME VARCHAR(40),
	EMAIL VARCHAR(40),
	TELEPHONE VARCHAR(13),
	CELLPHONE VARCHAR(14),
	PASSWORD_EMPLOYEE VARCHAR(255)
);